// Generated by qyvr-buzz-relay scripts/vendor-openclaw from commit 7aaee2003e4775eea4a9a465a75e46fee2ea2e0d. Do not edit.
// Types for @qyvr/buzz-kit (plain ESM JavaScript).
export interface NostrEvent { id: string; pubkey: string; created_at: number; kind: number; tags: string[][]; content: string; sig: string }
export interface EventTemplate { kind: number; content: string; tags: string[][]; created_at?: number }
export type AuthTag = [string, string, string, string];

export function generateKeypair(): { sk: string; pk: string };
export function pubkeyOf(skHex: string): string;
export function normalizePubkey(input: string): string;
export function npubOf(pkHex: string): string;
export function randomHex(bytes?: number): string;
export function signEvent(skHex: string, template: EventTemplate): NostrEvent;

export function preimageHash(agentPkHex: string, conditions: string): Uint8Array;
export function mintAuthTag(ownerSkHex: string, agentPkHex: string, conditions: string, auxRand?: Uint8Array): AuthTag;
export function windowConditions(nowSec: number, ttlSec?: number): string;
export function verifyAuthTag(tag: unknown, agentPkHex: string): string;

export function parseEnv(text: string): Map<string, string>;
export function fillEnv(templateText: string, existingText: string, opts?: { generators?: Record<string, () => string>; pinned?: Record<string, string> }): string;

export type TypedKind = 'brief' | 'ask' | 'grant' | 'artifact' | 'blocker' | 'decision' | 'claim' | 'receipt';
export const TYPES: readonly TypedKind[];
export function typedMessage(m: { channelId: string; type: TypedKind; n: number; summary: string; payload?: unknown }): EventTemplate;
export function readTyped(event: { tags?: string[][] }): { type: TypedKind; n: number; payload: any } | null;

export const NIP98_KIND: 27235;
export const NIP98_WINDOW_S: number;
export function signNip98(skHex: string, method: string, url: string, bodyText?: string): string;
export function verifyNip98(header: string | null | undefined, req: { method: string; url: string; bodyText?: string; now: number }): { pubkey: string; id: string };

export class RelayHttp {
  constructor(baseUrl: string, skHex: string, opts?: { authTag?: AuthTag | null; fetch?: typeof fetch; via?: { base: string; headers?: Record<string, string> } | null });
  submit(template: EventTemplate, opts?: { includeAuthTag?: boolean }): Promise<NostrEvent>;
  query(filters: Record<string, unknown>[]): Promise<NostrEvent[]>;
}
export function buildCreateChannel(c: { id: string; name: string; about?: string; ttl?: number | null }): EventTemplate;
export function buildAddMember(channel: string, pubkey: string, role?: string): EventTemplate;
export function buildRemoveMember(channel: string, pubkey: string): EventTemplate;
export function buildArchive(channel: string): EventTemplate;
export function buildBan(pubkey: string, reason?: string): EventTemplate;

export function toWsUrl(url: string): string;
export function openRelay(url: string, skHex: string, opts?: { authTag?: AuthTag | null; timeoutMs?: number }): Promise<{ publish(t: EventTemplate): Promise<NostrEvent>; query(f: Record<string, unknown>): Promise<NostrEvent[]>; close(): void }>;

export interface Profile { display_name?: string; name?: string; picture?: string; about?: string; nip05?: string }
export function buildProfile(fields: Profile): EventTemplate;
export function ensureProfile(relay: RelayHttp, wanted: Profile, opts?: { keepName?: boolean }): Promise<'published' | 'unchanged' | 'kept'>;
